# Generated by Django 3.2.8 on 2021-10-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('basedatetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.basedatetime')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('app1.basedatetime',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basedatetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.basedatetime')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('TaskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertask', to='app1.tasktype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertask', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app1.basedatetime',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('basedatetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.basedatetime')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('hyperlink', models.TextField(blank=True, null=True)),
                ('notification_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app1.task')),
            ],
            bases=('app1.basedatetime',),
        ),
    ]
