# Generated by Django 3.2.8 on 2021-10-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskType',
            new_name='task_type',
        ),
    ]
